/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Category {
    name: string;
    description: string;
    image?: string;
}
export type Status = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "checking";
    checking: {
        userPrincipal?: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
        userPrincipal?: string;
    };
};
export interface PaginationResult {
    currentPage: bigint;
    items: Array<Product>;
    totalPages: bigint;
    totalItems: bigint;
    hasNextPage: boolean;
    hasPrevPage: boolean;
}
export interface PaginationResult_1 {
    currentPage: bigint;
    items: Array<Category>;
    totalPages: bigint;
    totalItems: bigint;
    hasNextPage: boolean;
    hasPrevPage: boolean;
}
export interface Product {
    id: bigint;
    name: string;
    description: string;
    category: string;
    image?: string;
    price: bigint;
}
export interface CheckoutLineItem {
    product_id: bigint;
    quantity: bigint;
}
export interface backendInterface {
    addAdmin(newAdmin: Principal): Promise<void>;
    addAllowedOrigin(newOrigin: string): Promise<string>;
    addCategory(name: string, description: string, image: string | null): Promise<void>;
    addProduct(name: string, description: string, price: bigint, category: string, image: string | null): Promise<void>;
    addTransaction(session_id: string): Promise<Status | null>;
    clearAllCategories(): Promise<string>;
    clearAllProducts(): Promise<string>;
    clearAllTransactions(): Promise<string>;
    createCheckoutSession(lineItems: Array<CheckoutLineItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteCategory(name: string): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    deleteTransaction(session_id: string): Promise<boolean>;
    editProduct(id: bigint, name: string, description: string, price: bigint, category: string, image: string | null): Promise<void>;
    getAdmins(): Promise<Array<Principal>>;
    getAllCategories(): Promise<Array<string>>;
    getAllowedOrigins(): Promise<Array<string>>;
    getCategories(page: bigint | null, limit: bigint | null): Promise<PaginationResult_1>;
    getProducts(page: bigint | null, limit: bigint | null): Promise<PaginationResult>;
    getProductsByCategory(category: string, page: bigint | null, limit: bigint | null): Promise<PaginationResult>;
    getTransaction(session_id: string): Promise<Status | null>;
    getTransactionLineItems(session_id: string, starting_after: string | null): Promise<string>;
    getTransactions(): Promise<Array<[string, Status]>>;
    getTransactionsByPrincipal(): Promise<Array<[string, Status]>>;
    getUser(): Promise<string | null>;
    initializeAuth(): Promise<void>;
    initializeData(initCategories: Array<Category>, initProducts: Array<Product>, initAllowedOrigins: Array<string>): Promise<string>;
    isAdmin(): Promise<boolean>;
    removeAdmin(adminToRemove: Principal): Promise<void>;
    removeAllowedOrigin(originToRemove: string): Promise<string>;
    setAuthorization(newAuthorization: string): Promise<void>;
    setUser(name: string): Promise<void>;
    transform(arg0: {
        response: {
            status: bigint;
            body: Uint8Array;
            headers: Array<{
                value: string;
                name: string;
            }>;
        };
    }): Promise<{
        status: bigint;
        body: Uint8Array;
        headers: Array<{
            value: string;
            name: string;
        }>;
    }>;
}
import type { Category as _Category, PaginationResult as _PaginationResult, PaginationResult_1 as _PaginationResult_1, Product as _Product, Status as _Status } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async addAllowedOrigin(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addAllowedOrigin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAllowedOrigin(arg0);
            return result;
        }
    }
    async addCategory(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addTransaction(arg0: string): Promise<Status | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearAllCategories(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllCategories();
            return result;
        }
    }
    async clearAllProducts(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllProducts();
            return result;
        }
    }
    async clearAllTransactions(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllTransactions();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<CheckoutLineItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async editProduct(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async getAdmins(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmins();
            return result;
        }
    }
    async getAllCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllowedOrigins(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllowedOrigins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllowedOrigins();
            return result;
        }
    }
    async getCategories(arg0: bigint | null, arg1: bigint | null): Promise<PaginationResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PaginationResult_1_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PaginationResult_1_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(arg0: bigint | null, arg1: bigint | null): Promise<PaginationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PaginationResult_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PaginationResult_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: string, arg1: bigint | null, arg2: bigint | null): Promise<PaginationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PaginationResult_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PaginationResult_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: string): Promise<Status | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionLineItems(arg0: string, arg1: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionLineItems(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionLineItems(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getTransactions(): Promise<Array<[string, Status]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByPrincipal(): Promise<Array<[string, Status]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByPrincipal();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByPrincipal();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAuth(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAuth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAuth();
            return result;
        }
    }
    async initializeData(arg0: Array<Category>, arg1: Array<Product>, arg2: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeData(to_candid_vec_n22(this._uploadFile, this._downloadFile, arg0), to_candid_vec_n25(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeData(to_candid_vec_n22(this._uploadFile, this._downloadFile, arg0), to_candid_vec_n25(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async removeAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async removeAllowedOrigin(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAllowedOrigin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAllowedOrigin(arg0);
            return result;
        }
    }
    async setAuthorization(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAuthorization(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAuthorization(arg0);
            return result;
        }
    }
    async setUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUser(arg0);
            return result;
        }
    }
    async transform(arg0: {
        response: {
            status: bigint;
            body: Uint8Array;
            headers: Array<{
                value: string;
                name: string;
            }>;
        };
    }): Promise<{
        status: bigint;
        body: Uint8Array;
        headers: Array<{
            value: string;
            name: string;
        }>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_Category_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PaginationResult_1_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginationResult_1): PaginationResult_1 {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PaginationResult_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginationResult): PaginationResult {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Status]): Status | null {
    return value.length === 0 ? null : from_candid_Status_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPage: bigint;
    items: Array<_Category>;
    totalPages: bigint;
    totalItems: bigint;
    hasNextPage: boolean;
    hasPrevPage: boolean;
}): {
    currentPage: bigint;
    items: Array<Category>;
    totalPages: bigint;
    totalItems: bigint;
    hasNextPage: boolean;
    hasPrevPage: boolean;
} {
    return {
        currentPage: value.currentPage,
        items: from_candid_vec_n12(_uploadFile, _downloadFile, value.items),
        totalPages: value.totalPages,
        totalItems: value.totalItems,
        hasNextPage: value.hasNextPage,
        hasPrevPage: value.hasPrevPage
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    image: [] | [string];
}): {
    name: string;
    description: string;
    image?: string;
} {
    return {
        name: value.name,
        description: value.description,
        image: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPage: bigint;
    items: Array<_Product>;
    totalPages: bigint;
    totalItems: bigint;
    hasNextPage: boolean;
    hasPrevPage: boolean;
}): {
    currentPage: bigint;
    items: Array<Product>;
    totalPages: bigint;
    totalItems: bigint;
    hasNextPage: boolean;
    hasPrevPage: boolean;
} {
    return {
        currentPage: value.currentPage,
        items: from_candid_vec_n17(_uploadFile, _downloadFile, value.items),
        totalPages: value.totalPages,
        totalItems: value.totalItems,
        hasNextPage: value.hasNextPage,
        hasPrevPage: value.hasPrevPage
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    category: string;
    image: [] | [string];
    price: bigint;
}): {
    id: bigint;
    name: string;
    description: string;
    category: string;
    image?: string;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        category: value.category,
        image: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
}): {
    userPrincipal?: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.userPrincipal))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
    userPrincipal: [] | [string];
}): {
    error: string;
    userPrincipal?: string;
} {
    return {
        error: value.error,
        userPrincipal: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.userPrincipal))
    };
}
function from_candid_tuple_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Status]): [string, Status] {
    return [
        value[0],
        from_candid_Status_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    checking: {
        userPrincipal: [] | [string];
    };
} | {
    failed: {
        error: string;
        userPrincipal: [] | [string];
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "checking";
    checking: {
        userPrincipal?: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
        userPrincipal?: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n5(_uploadFile, _downloadFile, value.completed)
    } : "checking" in value ? {
        __kind__: "checking",
        checking: from_candid_record_n7(_uploadFile, _downloadFile, value.checking)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: from_candid_record_n8(_uploadFile, _downloadFile, value.failed)
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Status]>): Array<[string, Status]> {
    return value.map((x)=>from_candid_tuple_n21(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    image?: string;
}): {
    name: string;
    description: string;
    image: [] | [string];
} {
    return {
        name: value.name,
        description: value.description,
        image: value.image ? candid_some(value.image) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    category: string;
    image?: string;
    price: bigint;
}): {
    id: bigint;
    name: string;
    description: string;
    category: string;
    image: [] | [string];
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        category: value.category,
        image: value.image ? candid_some(value.image) : candid_none(),
        price: value.price
    };
}
function to_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Category>): Array<_Category> {
    return value.map((x)=>to_candid_Category_n23(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Product>): Array<_Product> {
    return value.map((x)=>to_candid_Product_n26(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
