import type { VolumePackage } from "@/types";

/* ─── Volume Boost Package Tiers ────────────────────────────────────────── */

export const VOLUME_PACKAGES: VolumePackage[] = [
  {
    id: "starter",
    name: "Starter Boost",
    targetVolume: 1_000,
    targetVolumeFmt: "$1K",
    solCost: 0.5,
    solCostFmt: "0.5 SOL",
    usdCost: "~$75",
    badge: null,
    description: "Ideal for small tokens — give your coin a first push.",
  },
  {
    id: "basic",
    name: "Basic Boost",
    targetVolume: 5_000,
    targetVolumeFmt: "$5K",
    solCost: 1.5,
    solCostFmt: "1.5 SOL",
    usdCost: "~$225",
    badge: null,
    description: "Get noticed on Pump.fun with healthy daily volume.",
  },
  {
    id: "standard",
    name: "Standard Boost",
    targetVolume: 10_000,
    targetVolumeFmt: "$10K",
    solCost: 2.5,
    solCostFmt: "2.5 SOL",
    usdCost: "~$375",
    badge: null,
    description: "Establish credibility and attract organic traders.",
  },
  {
    id: "growth",
    name: "Growth Boost",
    targetVolume: 25_000,
    targetVolumeFmt: "$25K",
    solCost: 4,
    solCostFmt: "4 SOL",
    usdCost: "~$600",
    badge: null,
    description: "Scale visibility and build momentum on Pump.fun.",
  },
  {
    id: "pro",
    name: "Pro Boost",
    targetVolume: 50_000,
    targetVolumeFmt: "$50K",
    solCost: 7,
    solCostFmt: "7 SOL",
    usdCost: "~$1,050",
    badge: "POPULAR",
    popular: true,
    description: "Most chosen — puts your token on Pump.fun trending.",
  },
  {
    id: "advanced",
    name: "Advanced Boost",
    targetVolume: 100_000,
    targetVolumeFmt: "$100K",
    solCost: 12,
    solCostFmt: "12 SOL",
    usdCost: "~$1,800",
    badge: "HOT",
    description: "Top 5 trending on Pump.fun within 60 minutes.",
  },
  {
    id: "elite",
    name: "Elite Boost",
    targetVolume: 500_000,
    targetVolumeFmt: "$500K",
    solCost: 25,
    solCostFmt: "25 SOL",
    usdCost: "~$3,750",
    badge: null,
    description: "Dominate the charts — #1 trending for 24h.",
  },
  {
    id: "premium",
    name: "Premium Boost",
    targetVolume: 2_000_000,
    targetVolumeFmt: "$2M",
    solCost: 50,
    solCostFmt: "50 SOL",
    usdCost: "~$7,500",
    badge: "WHALE",
    description: "Maximum impact — viral volume & market cap surge.",
  },
];
