import type { VolumePackage } from "@/types";

/* ─── Volume Boost Package Tiers ────────────────────────────────────────── */

export const VOLUME_PACKAGES: VolumePackage[] = [
  {
    id: "starter",
    name: "Starter Boost",
    targetVolume: 1_000,
    targetVolumeFmt: "$1K",
    solCost: 0.5,
    solCostFmt: "0.5 SOL",
    usdCost: "~$75",
    badge: null,
    description: "Ideal for small tokens — give your coin a first push.",
  },
  {
    id: "basic",
    name: "Basic Boost",
    targetVolume: 5_000,
    targetVolumeFmt: "$5K",
    solCost: 2,
    solCostFmt: "2 SOL",
    usdCost: "~$300",
    badge: null,
    description: "Get noticed on Pump.fun with healthy daily volume.",
  },
  {
    id: "standard",
    name: "Standard Boost",
    targetVolume: 10_000,
    targetVolumeFmt: "$10K",
    solCost: 3.5,
    solCostFmt: "3.5 SOL",
    usdCost: "~$525",
    badge: null,
    description: "Establish credibility and attract organic traders.",
  },
  {
    id: "pro",
    name: "Pro Boost",
    targetVolume: 25_000,
    targetVolumeFmt: "$25K",
    solCost: 8,
    solCostFmt: "8 SOL",
    usdCost: "~$1,200",
    badge: "POPULAR",
    popular: true,
    description: "Most chosen — puts your token on Pump.fun trending.",
  },
  {
    id: "elite",
    name: "Elite Boost",
    targetVolume: 50_000,
    targetVolumeFmt: "$50K",
    solCost: 14,
    solCostFmt: "14 SOL",
    usdCost: "~$2,100",
    badge: null,
    description: "Top 5 trending on Pump.fun within 60 minutes.",
  },
  {
    id: "mega",
    name: "Mega Boost",
    targetVolume: 100_000,
    targetVolumeFmt: "$100K",
    solCost: 25,
    solCostFmt: "25 SOL",
    usdCost: "~$3,750",
    badge: "HOT",
    description: "Dominate the charts — #1 trending for 24h.",
  },
  {
    id: "ultra",
    name: "Ultra Boost",
    targetVolume: 500_000,
    targetVolumeFmt: "$500K",
    solCost: 100,
    solCostFmt: "100 SOL",
    usdCost: "~$15,000",
    badge: null,
    description: "Institutional-grade volume for serious launches.",
  },
  {
    id: "premium",
    name: "Premium Boost",
    targetVolume: 2_000_000,
    targetVolumeFmt: "$2M",
    solCost: 350,
    solCostFmt: "350 SOL",
    usdCost: "~$52,500",
    badge: "WHALE",
    description: "Maximum impact — viral volume & market cap surge.",
  },
];
