/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BoostOrder {
  'ca' : string,
  'id' : string,
  'status' : BoostStatus,
  'solAmount' : number,
  'volumeTarget' : bigint,
  'createdAt' : bigint,
  'coinSymbol' : [] | [string],
  'tier' : BoostTier,
  'walletAddress' : string,
  'volumeAchieved' : bigint,
  'txHash' : string,
  'coinName' : [] | [string],
  'estimatedCompletionTime' : bigint,
}
export interface BoostProgress {
  'status' : BoostStatus,
  'volumeTarget' : bigint,
  'orderId' : string,
  'volumeAchieved' : bigint,
  'timeRemaining' : bigint,
  'percentComplete' : bigint,
}
export type BoostStatus = { 'Failed' : null } |
  { 'Active' : null } |
  { 'Processing' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type BoostTier = { 'Pro' : null } |
  { 'Elite' : null } |
  { 'Starter' : null } |
  { 'Premium' : null } |
  { 'Advanced' : null } |
  { 'Ultra' : null } |
  { 'Basic' : null } |
  { 'Growth' : null };
export interface LeaderboardEntry {
  'totalOrders' : bigint,
  'totalVolume' : bigint,
  'rank' : bigint,
  'walletAddress' : string,
  'displayWallet' : string,
}
export interface TierInfo {
  'name' : string,
  'tier' : BoostTier,
  'solCost' : number,
  'dollarTarget' : bigint,
  'estimatedHours' : bigint,
}
export interface _SERVICE {
  'getActiveBoosts' : ActorMethod<[], Array<BoostOrder>>,
  'getBoostOrder' : ActorMethod<[string], [] | [BoostOrder]>,
  'getBoostOrdersByWallet' : ActorMethod<[string], Array<BoostOrder>>,
  'getBoostProgress' : ActorMethod<[string], [] | [BoostProgress]>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getTierInfo' : ActorMethod<[], Array<TierInfo>>,
  'sendTelegramNotification' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setTelegramConfig' : ActorMethod<[string, string], undefined>,
  'simulateProgressUpdate' : ActorMethod<[], undefined>,
  'submitBoostOrder' : ActorMethod<[string, string, string], BoostOrder>,
  'submitBoostOrderWithCoin' : ActorMethod<
    [string, string, string, string, string],
    BoostOrder
  >,
  'submitTxHash' : ActorMethod<
    [string, string],
    { 'ok' : BoostOrder } |
      { 'err' : string }
  >,
  'updateBoostStatus' : ActorMethod<[string, string], boolean>,
  'verifyAndActivateBoost' : ActorMethod<
    [string],
    { 'ok' : BoostOrder } |
      { 'err' : string }
  >,
  'verifyTxHashOnChain' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];