/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BoostStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Active' : IDL.Null,
  'Processing' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const BoostTier = IDL.Variant({
  'Pro' : IDL.Null,
  'Elite' : IDL.Null,
  'Starter' : IDL.Null,
  'Premium' : IDL.Null,
  'Advanced' : IDL.Null,
  'Ultra' : IDL.Null,
  'Basic' : IDL.Null,
  'Growth' : IDL.Null,
});
export const BoostOrder = IDL.Record({
  'ca' : IDL.Text,
  'id' : IDL.Text,
  'status' : BoostStatus,
  'solAmount' : IDL.Float64,
  'volumeTarget' : IDL.Nat,
  'createdAt' : IDL.Int,
  'tier' : BoostTier,
  'walletAddress' : IDL.Text,
  'volumeAchieved' : IDL.Nat,
  'estimatedCompletionTime' : IDL.Int,
});
export const BoostProgress = IDL.Record({
  'status' : BoostStatus,
  'volumeTarget' : IDL.Nat,
  'orderId' : IDL.Text,
  'volumeAchieved' : IDL.Nat,
  'timeRemaining' : IDL.Int,
  'percentComplete' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalVolume' : IDL.Nat,
  'rank' : IDL.Nat,
  'walletAddress' : IDL.Text,
  'displayWallet' : IDL.Text,
});
export const TierInfo = IDL.Record({
  'name' : IDL.Text,
  'tier' : BoostTier,
  'solCost' : IDL.Float64,
  'dollarTarget' : IDL.Nat,
  'estimatedHours' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getActiveBoosts' : IDL.Func([], [IDL.Vec(BoostOrder)], ['query']),
  'getBoostOrder' : IDL.Func([IDL.Text], [IDL.Opt(BoostOrder)], ['query']),
  'getBoostOrdersByWallet' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BoostOrder)],
      ['query'],
    ),
  'getBoostProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BoostProgress)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getTierInfo' : IDL.Func([], [IDL.Vec(TierInfo)], ['query']),
  'simulateProgressUpdate' : IDL.Func([], [], []),
  'submitBoostOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [BoostOrder],
      [],
    ),
  'updateBoostStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BoostStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Active' : IDL.Null,
    'Processing' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const BoostTier = IDL.Variant({
    'Pro' : IDL.Null,
    'Elite' : IDL.Null,
    'Starter' : IDL.Null,
    'Premium' : IDL.Null,
    'Advanced' : IDL.Null,
    'Ultra' : IDL.Null,
    'Basic' : IDL.Null,
    'Growth' : IDL.Null,
  });
  const BoostOrder = IDL.Record({
    'ca' : IDL.Text,
    'id' : IDL.Text,
    'status' : BoostStatus,
    'solAmount' : IDL.Float64,
    'volumeTarget' : IDL.Nat,
    'createdAt' : IDL.Int,
    'tier' : BoostTier,
    'walletAddress' : IDL.Text,
    'volumeAchieved' : IDL.Nat,
    'estimatedCompletionTime' : IDL.Int,
  });
  const BoostProgress = IDL.Record({
    'status' : BoostStatus,
    'volumeTarget' : IDL.Nat,
    'orderId' : IDL.Text,
    'volumeAchieved' : IDL.Nat,
    'timeRemaining' : IDL.Int,
    'percentComplete' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalVolume' : IDL.Nat,
    'rank' : IDL.Nat,
    'walletAddress' : IDL.Text,
    'displayWallet' : IDL.Text,
  });
  const TierInfo = IDL.Record({
    'name' : IDL.Text,
    'tier' : BoostTier,
    'solCost' : IDL.Float64,
    'dollarTarget' : IDL.Nat,
    'estimatedHours' : IDL.Nat,
  });
  
  return IDL.Service({
    'getActiveBoosts' : IDL.Func([], [IDL.Vec(BoostOrder)], ['query']),
    'getBoostOrder' : IDL.Func([IDL.Text], [IDL.Opt(BoostOrder)], ['query']),
    'getBoostOrdersByWallet' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BoostOrder)],
        ['query'],
      ),
    'getBoostProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BoostProgress)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getTierInfo' : IDL.Func([], [IDL.Vec(TierInfo)], ['query']),
    'simulateProgressUpdate' : IDL.Func([], [], []),
    'submitBoostOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [BoostOrder],
        [],
      ),
    'updateBoostStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };