/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'checking' : IDL.Record({ 'userPrincipal' : IDL.Opt(IDL.Text) }),
  'failed' : IDL.Record({
    'error' : IDL.Text,
    'userPrincipal' : IDL.Opt(IDL.Text),
  }),
});
export const CheckoutLineItem = IDL.Record({
  'product_id' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(IDL.Text),
});
export const PaginationResult_1 = IDL.Record({
  'currentPage' : IDL.Nat,
  'items' : IDL.Vec(Category),
  'totalPages' : IDL.Nat,
  'totalItems' : IDL.Nat,
  'hasNextPage' : IDL.Bool,
  'hasPrevPage' : IDL.Bool,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const PaginationResult = IDL.Record({
  'currentPage' : IDL.Nat,
  'items' : IDL.Vec(Product),
  'totalPages' : IDL.Nat,
  'totalItems' : IDL.Nat,
  'hasNextPage' : IDL.Bool,
  'hasPrevPage' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addAllowedOrigin' : IDL.Func([IDL.Text], [IDL.Text], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Status)], []),
  'clearAllCategories' : IDL.Func([], [IDL.Text], []),
  'clearAllProducts' : IDL.Func([], [IDL.Text], []),
  'clearAllTransactions' : IDL.Func([], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(CheckoutLineItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'editProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllowedOrigins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCategories' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginationResult_1],
      ['query'],
    ),
  'getProducts' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginationResult],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginationResult],
      ['query'],
    ),
  'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Status)], ['query']),
  'getTransactionLineItems' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'getTransactions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Status))],
      ['query'],
    ),
  'getTransactionsByPrincipal' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Status))],
      ['query'],
    ),
  'getUser' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'initializeAuth' : IDL.Func([], [], []),
  'initializeData' : IDL.Func(
      [IDL.Vec(Category), IDL.Vec(Product), IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'removeAllowedOrigin' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setAuthorization' : IDL.Func([IDL.Text], [], []),
  'setUser' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [
        IDL.Record({
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'checking' : IDL.Record({ 'userPrincipal' : IDL.Opt(IDL.Text) }),
    'failed' : IDL.Record({
      'error' : IDL.Text,
      'userPrincipal' : IDL.Opt(IDL.Text),
    }),
  });
  const CheckoutLineItem = IDL.Record({
    'product_id' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const Category = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(IDL.Text),
  });
  const PaginationResult_1 = IDL.Record({
    'currentPage' : IDL.Nat,
    'items' : IDL.Vec(Category),
    'totalPages' : IDL.Nat,
    'totalItems' : IDL.Nat,
    'hasNextPage' : IDL.Bool,
    'hasPrevPage' : IDL.Bool,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const PaginationResult = IDL.Record({
    'currentPage' : IDL.Nat,
    'items' : IDL.Vec(Product),
    'totalPages' : IDL.Nat,
    'totalItems' : IDL.Nat,
    'hasNextPage' : IDL.Bool,
    'hasPrevPage' : IDL.Bool,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addAllowedOrigin' : IDL.Func([IDL.Text], [IDL.Text], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Status)], []),
    'clearAllCategories' : IDL.Func([], [IDL.Text], []),
    'clearAllProducts' : IDL.Func([], [IDL.Text], []),
    'clearAllTransactions' : IDL.Func([], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(CheckoutLineItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'editProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllowedOrigins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCategories' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginationResult_1],
        ['query'],
      ),
    'getProducts' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginationResult],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginationResult],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Status)], ['query']),
    'getTransactionLineItems' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'getTransactions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Status))],
        ['query'],
      ),
    'getTransactionsByPrincipal' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Status))],
        ['query'],
      ),
    'getUser' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'initializeAuth' : IDL.Func([], [], []),
    'initializeData' : IDL.Func(
        [IDL.Vec(Category), IDL.Vec(Product), IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'removeAllowedOrigin' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setAuthorization' : IDL.Func([IDL.Text], [], []),
    'setUser' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [
          IDL.Record({
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };