/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TierInfo {
    name: string;
    tier: BoostTier;
    solCost: number;
    dollarTarget: bigint;
    estimatedHours: bigint;
}
export interface LeaderboardEntry {
    totalOrders: bigint;
    totalVolume: bigint;
    rank: bigint;
    walletAddress: string;
    displayWallet: string;
}
export interface BoostProgress {
    status: BoostStatus;
    volumeTarget: bigint;
    orderId: string;
    volumeAchieved: bigint;
    timeRemaining: bigint;
    percentComplete: bigint;
}
export interface BoostOrder {
    ca: string;
    id: string;
    status: BoostStatus;
    solAmount: number;
    volumeTarget: bigint;
    createdAt: bigint;
    coinSymbol?: string;
    tier: BoostTier;
    walletAddress: string;
    volumeAchieved: bigint;
    txHash: string;
    coinName?: string;
    estimatedCompletionTime: bigint;
}
export enum BoostStatus {
    Failed = "Failed",
    Active = "Active",
    Processing = "Processing",
    Completed = "Completed",
    Pending = "Pending"
}
export enum BoostTier {
    Pro = "Pro",
    Elite = "Elite",
    Starter = "Starter",
    Premium = "Premium",
    Advanced = "Advanced",
    Ultra = "Ultra",
    Basic = "Basic",
    Growth = "Growth"
}
export interface backendInterface {
    getActiveBoosts(): Promise<Array<BoostOrder>>;
    getBoostOrder(orderId: string): Promise<BoostOrder | null>;
    getBoostOrdersByWallet(walletAddress: string): Promise<Array<BoostOrder>>;
    getBoostProgress(orderId: string): Promise<BoostProgress | null>;
    getLeaderboard(limit: bigint): Promise<Array<LeaderboardEntry>>;
    getTierInfo(): Promise<Array<TierInfo>>;
    sendTelegramNotification(orderId: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setTelegramConfig(botToken: string, chatId: string): Promise<void>;
    simulateProgressUpdate(): Promise<void>;
    submitBoostOrder(ca: string, tier: string, walletAddress: string): Promise<BoostOrder>;
    submitBoostOrderWithCoin(ca: string, tier: string, walletAddress: string, coinName: string, coinSymbol: string): Promise<BoostOrder>;
    submitTxHash(orderId: string, txHash: string): Promise<{
        __kind__: "ok";
        ok: BoostOrder;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateBoostStatus(orderId: string, status: string): Promise<boolean>;
    verifyAndActivateBoost(orderId: string): Promise<{
        __kind__: "ok";
        ok: BoostOrder;
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifyTxHashOnChain(txHash: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { BoostOrder as _BoostOrder, BoostProgress as _BoostProgress, BoostStatus as _BoostStatus, BoostTier as _BoostTier, TierInfo as _TierInfo } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getActiveBoosts(): Promise<Array<BoostOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveBoosts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveBoosts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBoostOrder(arg0: string): Promise<BoostOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoostOrder(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoostOrder(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBoostOrdersByWallet(arg0: string): Promise<Array<BoostOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoostOrdersByWallet(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoostOrdersByWallet(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBoostProgress(arg0: string): Promise<BoostProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoostProgress(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoostProgress(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return result;
        }
    }
    async getTierInfo(): Promise<Array<TierInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTierInfo();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTierInfo();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendTelegramNotification(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTelegramNotification(arg0);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTelegramNotification(arg0);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async setTelegramConfig(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTelegramConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTelegramConfig(arg0, arg1);
            return result;
        }
    }
    async simulateProgressUpdate(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.simulateProgressUpdate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simulateProgressUpdate();
            return result;
        }
    }
    async submitBoostOrder(arg0: string, arg1: string, arg2: string): Promise<BoostOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBoostOrder(arg0, arg1, arg2);
                return from_candid_BoostOrder_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBoostOrder(arg0, arg1, arg2);
            return from_candid_BoostOrder_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitBoostOrderWithCoin(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<BoostOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBoostOrderWithCoin(arg0, arg1, arg2, arg3, arg4);
                return from_candid_BoostOrder_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBoostOrderWithCoin(arg0, arg1, arg2, arg3, arg4);
            return from_candid_BoostOrder_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitTxHash(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: BoostOrder;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTxHash(arg0, arg1);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTxHash(arg0, arg1);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBoostStatus(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBoostStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBoostStatus(arg0, arg1);
            return result;
        }
    }
    async verifyAndActivateBoost(arg0: string): Promise<{
        __kind__: "ok";
        ok: BoostOrder;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAndActivateBoost(arg0);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAndActivateBoost(arg0);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyTxHashOnChain(arg0: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyTxHashOnChain(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyTxHashOnChain(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BoostOrder_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BoostOrder): BoostOrder {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_BoostProgress_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BoostProgress): BoostProgress {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_BoostStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BoostStatus): BoostStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_BoostTier_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BoostTier): BoostTier {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TierInfo_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TierInfo): TierInfo {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BoostProgress]): BoostProgress | null {
    return value.length === 0 ? null : from_candid_BoostProgress_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BoostOrder]): BoostOrder | null {
    return value.length === 0 ? null : from_candid_BoostOrder_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BoostStatus;
    volumeTarget: bigint;
    orderId: string;
    volumeAchieved: bigint;
    timeRemaining: bigint;
    percentComplete: bigint;
}): {
    status: BoostStatus;
    volumeTarget: bigint;
    orderId: string;
    volumeAchieved: bigint;
    timeRemaining: bigint;
    percentComplete: bigint;
} {
    return {
        status: from_candid_BoostStatus_n4(_uploadFile, _downloadFile, value.status),
        volumeTarget: value.volumeTarget,
        orderId: value.orderId,
        volumeAchieved: value.volumeAchieved,
        timeRemaining: value.timeRemaining,
        percentComplete: value.percentComplete
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    tier: _BoostTier;
    solCost: number;
    dollarTarget: bigint;
    estimatedHours: bigint;
}): {
    name: string;
    tier: BoostTier;
    solCost: number;
    dollarTarget: bigint;
    estimatedHours: bigint;
} {
    return {
        name: value.name,
        tier: from_candid_BoostTier_n7(_uploadFile, _downloadFile, value.tier),
        solCost: value.solCost,
        dollarTarget: value.dollarTarget,
        estimatedHours: value.estimatedHours
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ca: string;
    id: string;
    status: _BoostStatus;
    solAmount: number;
    volumeTarget: bigint;
    createdAt: bigint;
    coinSymbol: [] | [string];
    tier: _BoostTier;
    walletAddress: string;
    volumeAchieved: bigint;
    txHash: string;
    coinName: [] | [string];
    estimatedCompletionTime: bigint;
}): {
    ca: string;
    id: string;
    status: BoostStatus;
    solAmount: number;
    volumeTarget: bigint;
    createdAt: bigint;
    coinSymbol?: string;
    tier: BoostTier;
    walletAddress: string;
    volumeAchieved: bigint;
    txHash: string;
    coinName?: string;
    estimatedCompletionTime: bigint;
} {
    return {
        ca: value.ca,
        id: value.id,
        status: from_candid_BoostStatus_n4(_uploadFile, _downloadFile, value.status),
        solAmount: value.solAmount,
        volumeTarget: value.volumeTarget,
        createdAt: value.createdAt,
        coinSymbol: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.coinSymbol)),
        tier: from_candid_BoostTier_n7(_uploadFile, _downloadFile, value.tier),
        walletAddress: value.walletAddress,
        volumeAchieved: value.volumeAchieved,
        txHash: value.txHash,
        coinName: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.coinName)),
        estimatedCompletionTime: value.estimatedCompletionTime
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BoostOrder;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BoostOrder;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BoostOrder_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Failed: null;
} | {
    Active: null;
} | {
    Processing: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): BoostStatus {
    return "Failed" in value ? BoostStatus.Failed : "Active" in value ? BoostStatus.Active : "Processing" in value ? BoostStatus.Processing : "Completed" in value ? BoostStatus.Completed : "Pending" in value ? BoostStatus.Pending : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pro: null;
} | {
    Elite: null;
} | {
    Starter: null;
} | {
    Premium: null;
} | {
    Advanced: null;
} | {
    Ultra: null;
} | {
    Basic: null;
} | {
    Growth: null;
}): BoostTier {
    return "Pro" in value ? BoostTier.Pro : "Elite" in value ? BoostTier.Elite : "Starter" in value ? BoostTier.Starter : "Premium" in value ? BoostTier.Premium : "Advanced" in value ? BoostTier.Advanced : "Ultra" in value ? BoostTier.Ultra : "Basic" in value ? BoostTier.Basic : "Growth" in value ? BoostTier.Growth : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BoostOrder>): Array<BoostOrder> {
    return value.map((x)=>from_candid_BoostOrder_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TierInfo>): Array<TierInfo> {
    return value.map((x)=>from_candid_TierInfo_n14(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
